### ISSUE TITLE
why should flip the right eye image horizontally?

### ISSUE THREAD

**Issue by linccnu** [HzDmS/gaze_redirection#6]
Hello, i can not very clearly understand why should flip the right eye image horizontally as mentioned in the paper and source code.
https://github.com/HzDmS/gaze_redirection/blob/549b39930e1fe9bb02737cdd7ebb70c6583d14ba/src/data_loader.py#L122

And the meaning of the file name suffix('L' or 'R') in the dataset, what's the corresponding relation?

Thx~

**Comment by thoppe** [comment]
Hi @linccnu, I'm not the author but I've played with the repo a bit. L and R correspond to Left and Right eyes respectively. My guess on why the R eye needs to be flipped is to have a consistent dataset for training. If you're familiar with stylegan, we find that centering the face helps training ... a lot! Flipping the eyes so that the cornea is on the same side is similar to this.
